<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>FastFs.PowerShell</AssemblyName>
    <RootNamespace>FastFs.PowerShell</RootNamespace>
    <PowerShellHome Condition="'$(PowerShellHome)' == ''">C:\Program Files\PowerShell\7</PowerShellHome>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Management.Automation">
      <HintPath>$(PowerShellHome)\System.Management.Automation.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>

